### ISSUE TITLE
When article has not been crawled yet: change text to "processing"

### ISSUE THREAD

**Issue by n-kb** [jplusplus/CrawlerToolkit#12]
What happened:
 - I added the Twitter feed
 - I forced refresh
 - I saw a list of tweets with "no tags detected", "no title detected" etc. on the "Articles" page. 

I assumed that the crawler failed to crawl bitlinks and ifttt links - my bad. But we'd need better wording to explain that.

**Comment by pbellon** [comment]
I've added multiple "feedback" by enhanced usage of states (i.e. when downloading resources, when preservation tags have been detected and thus should - or shouldn't - be preserved, etc). However I observed some bottlenecks concerning resources downloading / processing and I still need to improve how and when I update status, that's why I opened #20 ticket.
